apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cd-sample-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_ME/cd-learning.git
    targetRevision: main
    path: argocd-app/manifests/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: cd-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
